### ISSUE TITLE
ModuleNotFoundError - 'MessageSerializer', also 'MockSchemaRegistryClient'

### ISSUE THREAD

**Issue by alexxtasi** [verisign/python-confluent-schemaregistry#11]
Hi all
I am trying to use ```python-confluent-schemaregistry``` package.
Since ```pip install``` is not available, I did a ```git clone``` and then used the ```python setup.py install``` method.

The installation ended successfully with:
```Finished processing dependencies for confluent-schemaregistry==0.1.1```

But when creating some python 3 code like:
```python
from confluent.schemaregistry.serializers import MessageSerializer, Util
from confluent.schemaregistry.client import CachedSchemaRegistryClient
```
or even 
```python
import confluent.schemaregistry.serializers
```

python cannot find both ```MessageSerializer``` and ```MockSchemaRegistryClient``` modules:
```python
>>> from confluent.schemaregistry.client import CachedSchemaRegistryClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/kafka-test/python-confluent-schemaregistry/confluent/schemaregistry/client/__init__.py", line 17, in <module>
    from MockSchemaRegistryClient import *
ModuleNotFoundError: No module named 'MockSchemaRegistryClient'
```
```python
>>> from confluent.schemaregistry.serializers import MessageSerializer, Util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/kafka-test/python-confluent-schemaregistry/confluent/schemaregistry/serializers/__init__.py", line 12, in <module>
    from MessageSerializer import *
ModuleNotFoundError: No module named 'MessageSerializer'
```
This happens when installing the package system-wide and also in a virtualenv
And in python 3.5 and 3.6 also !!

any help on this issue ? Or is there a mistake on my side ?
regards

**Comment by alexxtasi** [comment]
Apologize cause I was trying to use this by mistake, in python3 and not python2.
And more apologize for not mentioning it as long I realised it, but now... after some months!!

... closing it...
